name: Deployment

on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Get current release version
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Get slug variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Set environment variable names based on branch
      run: |
        echo "SECRET_NAME=/thefarmminneapolis/github/${GITHUB_REF_SLUG}" >> $GITHUB_ENV

    - name: Read secrets from AWS Secrets Manager into environment variables
      uses: say8425/aws-secrets-manager-actions@v2
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        SECRET_NAME: ${{ env.SECRET_NAME }}

    - name: Add public IP to AWS security group
      uses: sohelamin/aws-security-group-add-ip-action@master
      with:
        aws-access-key-id: ${{ secrets.THEFARMMINNEAPOLIS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.THEFARMMINNEAPOLIS_AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
        aws-security-group-id: ${{ env.SECURITY_GROUP_ID }}
        port: '22'
        to-port: '22'
        protocol: 'tcp'
        description: 'GitHub Action'

    - name: Update Composer
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        port: ${{ env.SSH_PORT }}
        script: |
          WP_ROOT="${{ env.PATH }}"
          composer require -d "$WP_ROOT" -n thefarmminneapolis/wp-migrate-db-pro-tweaks:${{ steps.get_version.outputs.version-without-v }}
