name: Release

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Get slug variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_AUTHOR_NAME: The Farm & The Odd Fellows
        GIT_AUTHOR_EMAIL: thefarmminneapolis@gmail.com
      with:
        extra_plugins: |
          @semantic-release/exec
          @semantic-release/changelog
          @semantic-release/git
          @saithodev/semantic-release-backmerge
